name: frontend
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  
  # Add this line for beautiful animations
  flutter_animate: ^4.5.0  
   # Add this for swipe actions
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true